spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    show-sql: true
  redis:
    cluster:
      nodes:
        - 127.0.0.1:6379
  messages:
    basename: i18n/message
    encoding: UTF-8
  jwt:
    secret: '{cipher}AQBIwpbFQoTDaR2+y/iiJq4I3frCpsj1PjH+WYHahbhblljZj/ZvFp9WsNC7LjKxo9NCB7cPAWh8Zc2i8FSFM1KfX7ncmeQxJNABtmlIPJ2Fw8PILT0SZuhnYg4IGBlryIXwvkjnqLNTUYqJ/Y8dThOsWAuLuEQE0EpzZaJgVgC5/LkJDC2eAeuTvAhFKY+tKGB03ZVUIetxDtAs3M0FH+65JGZz8s59O/ppv2KznQFyB+W7Wd6nu2IBjtAdOtzDvodOrsCbeJWZ0AdKEOWqtYTEtrkh3phWwQgOtE+hxwqmD7549VrQjVatmv2gXbW0/muz/SuqpGhCbyaYJvLV/CIDS261nXEOzmlmOLLeRWBiBuZEudYLK6y7pnXh9K8zzYA='
  social:
    kakao:
      client_id: 98c1b87a283bea5899e4d9f5cd606133
      redirect: /api/social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  url:
    base: http://localhost:9100
  mail:
    host: smtp.gmail.com
    port: 587
    username: caker.lcc@gmail.com
    password: '{cipher}AQAjBlqi1mpRapq2ExcxdXplOibSyz/Lt/Mgl9GT9RxLNTYhX841LpYjkH3J+eXnWZ7eZ6KAFfdFhyG/Vqv6RKBIOtlsb/0uNY/+4B8uYeI1DevF1mOWY7mlH5okNUaoiHECB2X/YZ9EDW5JPHxk5VRIrdLIQwRai0dCru4j2u3s0sWOdie5tl4mjMm/4yvp0ls/yC7Tl6Piwfzr2SmowE0IBjBUq4K8o3svwO4dZUDB2qliPLhbp5O+6tuWSYzPP6FuWasaFt2IVpb16SwAyrovWO6QDLEAxMZLLi4JHN1/jt/jC27VDFNCybbnmj8QuNaPdhzgbsR8NszmfJLMsWyC2dFYTUILRBSDojdpVL0wQszrzBRj4R2FdsqrgP2nD7MQkY8pavzNtciytPKlKBV+'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true