spring:
  profiles: local
zuul:
  routes:
    api:
      strip-prefix: false
      path: /api/**
      url: caker-api-service
      sensitive-headers: Cookie,Set-Cookie
    auth:
      strip-prefix: false
      path: /auth/**
      url: caker-auth-service
      sensitive-headers: Cookie,Set-Cookie