server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-store-password: localhost
    key-alias: localhost
spring:
  profiles: local
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
zuul:
  routes:
    api:
      strip-prefix: false
      path: /api/**
      url: caker-api-service
      sensitive-headers: Cookie,Set-Cookie
    auth:
      strip-prefix: false
      path: /auth/**
      url: caker-auth-service
      sensitive-headers: Cookie,Set-Cookie