server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-store-password: localhost
    key-alias: localhost
spring:
  profiles: local
zuul:
  routes:
    api:
      strip-prefix: false
      path: /api/**
      url: caker-api-service
      sensitive-headers: Cookie,Set-Cookie
    auth:
      strip-prefix: false
      path: /auth/**
      url: caker-auth-service
      sensitive-headers: Cookie,Set-Cookie
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown, info