server:
  port: 8090
  message: connected

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/caker?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    validation-query: SELECT 1
    validation-query-timeout: 1000
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: create
    generate-ddl: true
    open-in-view: false
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: raingurl
  social:
    kakao:
      client_id: 57e8ef720b40983fe335f85ba973e430
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  url:
    base: http://localhost:8090
  path:
    image-path: /image/