
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/caker?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: '{cipher}AQB++sQkvsl7O8ERml5jEWVZZVsClMykWGebEPKv8U0rOMVFZ+QJIZxYvH5CDm+5XI9dvtbJICmNEVTS4ej0TmBm0Jc1jSbS2q/FLkh6tUrnCHew75wonSDqOH07vKTYhZyHICRDivlYl7gRtzzrA0fmO6M0SB12P8Z53NFgQ+CEXg9NCvbqxiMlYH6HFNLNEkb40cOJgD42G5KhWJvl3D/LhUmudsFICTM0glKsRHfzfxEGb9kwCAHc7dUtJaAl7hp0rN1QZz76bYdxX2kOovGpNdzkme2jfzhJueOnIqII/usvx8xgRkZ/XyV3Q/xlH1ZM75IeRDNsZa9if0jS8vFdQsDBNqmQZGce+iz+jS6InRgEMg/WyR9MlBlc759zBYk='
    driver-class-name: com.mysql.cj.jdbc.Driver
    validation-query: SELECT 1
    validation-query-timeout: 1000
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: create
    generate-ddl: true
    open-in-view: false
  messages:
    basename: i18n/message
    encoding: UTF-8
  jwt:
    secret: '{cipher}AQBIwpbFQoTDaR2+y/iiJq4I3frCpsj1PjH+WYHahbhblljZj/ZvFp9WsNC7LjKxo9NCB7cPAWh8Zc2i8FSFM1KfX7ncmeQxJNABtmlIPJ2Fw8PILT0SZuhnYg4IGBlryIXwvkjnqLNTUYqJ/Y8dThOsWAuLuEQE0EpzZaJgVgC5/LkJDC2eAeuTvAhFKY+tKGB03ZVUIetxDtAs3M0FH+65JGZz8s59O/ppv2KznQFyB+W7Wd6nu2IBjtAdOtzDvodOrsCbeJWZ0AdKEOWqtYTEtrkh3phWwQgOtE+hxwqmD7549VrQjVatmv2gXbW0/muz/SuqpGhCbyaYJvLV/CIDS261nXEOzmlmOLLeRWBiBuZEudYLK6y7pnXh9K8zzYA='
  social:
    kakao:
      client_id: 98c1b87a283bea5899e4d9f5cd606133
      redirect: /api/social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  url:
    base: https://localhost:8443
  mail:
    host: smtp.gmail.com
    port: 587
    username: caker.lcc@gmail.com
    password: '{cipher}AQAjBlqi1mpRapq2ExcxdXplOibSyz/Lt/Mgl9GT9RxLNTYhX841LpYjkH3J+eXnWZ7eZ6KAFfdFhyG/Vqv6RKBIOtlsb/0uNY/+4B8uYeI1DevF1mOWY7mlH5okNUaoiHECB2X/YZ9EDW5JPHxk5VRIrdLIQwRai0dCru4j2u3s0sWOdie5tl4mjMm/4yvp0ls/yC7Tl6Piwfzr2SmowE0IBjBUq4K8o3svwO4dZUDB2qliPLhbp5O+6tuWSYzPP6FuWasaFt2IVpb16SwAyrovWO6QDLEAxMZLLi4JHN1/jt/jC27VDFNCybbnmj8QuNaPdhzgbsR8NszmfJLMsWyC2dFYTUILRBSDojdpVL0wQszrzBRj4R2FdsqrgP2nD7MQkY8pavzNtciytPKlKBV+'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
elastic:
  url: http://localhost:9200
  indices:
    tag: caker-tag
  api:
    search: _search
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown, info